src/Fibonacci.Web/Controllers/FibonacciController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fibonacci.Web.Controllers
{
    public class FibonacciController : Controller
    {
        [HttpPut("~/fibonacci/{numberOfTerms}")]
        public IActionResult Calculate([FromRoute]int numberOfTerms)
        {
            var result = new FibonacciCalculator().Calculate(numberOfTerms);
            return Ok(result);
        }
    }
}

src/Fibonacci.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fibonacci.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/Fibonacci.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Fibonacci.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Fibonacci.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h2>Calculate Fibonacci numbers</h2>
        <p>
            Calculate the Fibonacci sequence to the <em>n</em>th term. As the Fibonacci
            sequence is <em>O(n!)</em>, calculating the sequence beyond 20 terms will
            take noticeably longer lengths of time. 20 terms should be calculable in
            around 2.5s.
        </p>
        <form method="PUT" action="@Url.Action("Calculate", "Fibonacci",  new { numberOfTerms = "{numberOfTerms}"})" class="form-inline" id="calculator">
            <div class="form-group">
                <label for="terms">Number of terms</label>
                <input type="text" id="terms" class="form-control" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    Calculate!
                </button>
            </div>
        </form>
        <div id="series">
            <img src="@Url.Content("images/ajax-loader.gif")" style="display: none;" id="spinner" />
            <p></p>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var form = document.querySelector("#calculator");
        function calculate(event) {
            console.log("FIRED!");
            event.preventDefault();
            let numberOfTerms = document.querySelector("#terms").value;

            let results = document.querySelector("#series p");
            let spinner = document.querySelector("#spinner");
            spinner.style = "display: visible;";
            results.style = "display: none;"

            let url = decodeURI(form.action).replace("{numberOfTerms}", numberOfTerms);
            let method = form.getAttribute("method");
            fetch(url, {
                method: method
            }).then(function(response) {
                spinner.style = "display: none;";
                results.style = "display: visible;";
                
                if (response.ok) {
                    return response.text();
                } else {
                    return `${response.status} ${response.statusText}`;
                }
            }).then(function(body){
                results.textContent = body;
            }).catch(function(error) {
                spinner.style = "display: none;";
                results.style = "display: visible;";
                results.textContent = error.message;
            });

            return false;
        }
        form.onsubmit = calculate;
    </script>
}

src/Fibonacci.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Fibonacci.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Fibonacci.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Fibonacci.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>